language: node_js

node_js:
  - "20.12.2"

addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - npm ci

before_script:
  - node --version
  - npm --version

script:
  - npx cypress verify
  - npx cypress run
