name: Execute cypress tests

on:
  push:
  workflow_dispatch:

jobs:
  execute-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: npm install

      - name: Executer les tests
        run: npx cypress run

  execute-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer newman
        run: npm install -g newman

      - name: Executer les tests postman
        run: newman run postman/collection.json
